config/routes.rb
Rails.application.routes.draw do
  get 'gif/cool'

  get 'gif/free'

  root to: 'gif#cool'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'  
  get '/sweet' => 'gif#sweet'  
   

  
  
  resources :estudios
  resources :eventos
  resources :compromissos
  resources :disciplinas
  resources :professores
  resources :welcome#index

end

app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
  validates_presence_of :titulo, :message => " - deve ser preenchido"
  validates_presence_of :texto, :message => "deve ser preenchido"	
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  has_many :disciplinas_mestres
  has_many :mestres, :through => :disciplinas_mestres
  has_many :eventos
  validates_presence_of :nome, :message => "- deve ser informado"

  validates_uniqueness_of :nome, :message => "Nome já informado"
	
end

app/models/disciplina_mestre.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/disciplina_professor.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  belongs_to :estudio
  validates_presence_of :data, :message => "Data deve ser preenchdida"
  validates_presence_of :hora_inicial, :message => "hora inicial deve ser informada"
  validates_presence_of :hora_final, :message => "hora final deve ser informada"  	
end

app/models/mestre.rb
class Mestre < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/estudios_controller.rb
class EstudiosController < ApplicationController
  before_filter :authorize
  before_action :set_estudio, only: [:show, :edit, :update, :destroy]
  
  # GET /estudios
  # GET /estudios.json
  def index
    if params[:search]                        
      @estudios = Estudio.where("nome like ?", "%#{params[:search]}%")
    else 
      #@estudios = Estudio.all
      @estudios = Estudio.all.page(params['page']).per(5)
    end
  end

  # GET /estudios/1
  # GET /estudios/1.json
  def show
  end

  # GET /estudios/new
  def new
    @estudio = Estudio.new
  end

  # GET /estudios/1/edit
  def edit
  end

  # POST /estudios
  # POST /estudios.json
  def create
    @estudio = Estudio.new(estudio_params)

    respond_to do |format|
      if @estudio.save
        format.html { redirect_to @estudio, notice: 'estudio was successfully created.' }
        format.json { render :show, status: :created, location: @estudio }
      else
        format.html { render :new }
        format.json { render json: @estudio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudios/1
  # PATCH/PUT /estudios/1.json
  def update
    respond_to do |format|
      if @estudio.update(estudio_params)
        format.html { redirect_to @estudio, notice: 'estudio was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudio }
      else
        format.html { render :edit }
        format.json { render json: @estudio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudios/1
  # DELETE /estudios/1.json
  def destroy
    @estudio.destroy
    respond_to do |format|
      format.html { redirect_to estudios_url, notice: 'estudio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudio
      @estudio = Estudio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudio_params
      params.require(:estudio).permit(:nome, :endereco)
    end
end

app/controllers/gif_controller.rb
class GifController < ApplicationController
  before_filter :authorize
  def cool
    redirect_to '/welcome#index'
  end

  def free
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compromissos_helper.rb
module CompromissosHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/mestres_helper.rb
module MestresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/estudios/_admin_index.html.erb
<%- model_class = Estudio -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @estudios.each do |estudio| %>
      <tr>
        <td><%= link_to estudio.id, estudio_path(estudio) %></td>
        <td><%= estudio.nome %></td>
        <td><%= estudio.endereco %></td>
        <td>
          <%= link_to t('.show', :default => t("herpers.links.show")), estudio_path(estudio), :class => 'btn btn-success btn-xs'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estudio_path(estudio), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estudio_path(estudio),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @estudios %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estudio_path,
            :class => 'btn btn-primary' %>

app/views/estudios/_form.html.erb
<%= form_for @estudio, :html => { :class => "form-horizontal estudio" } do |f| %>

  <% if @estudio.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@estudio.errors.count, "error") %> prohibited this estudio from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @estudio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :endereco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endereco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endereco) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                estudios_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/estudios/_normal_user_index.html.erb
<%- model_class = Estudio -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
    </tr>
  </thead>
  <tbody>
    <% @estudios.each do |estudio| %>
      <tr>
        <td><%= link_to estudio.id, estudio_path(estudio) %></td>
        <td><%= estudio.nome %></td>
        <td><%= estudio.endereco %></td>
        <td>
          <%= link_to t('.show', :default => t("herpers.links.show")), estudio_path(estudio), :class => 'btn btn-success btn-xs'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estudio_path(estudio), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estudio_path(estudio),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>
<%# paginate @estudios %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estudio_path,
            :class => 'btn btn-primary' %>

app/views/estudios/edit.html.erb
<%- model_class = Estudio -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estudios/index.html.erb
<%- model_class = Estudio -%>
<%= form_tag(estudios_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Entre com sua busca' %>
  <%= submit_tag "Search" %>
<% end %>
<p id="notice" <%= notice %></p>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= render partial: "normal_user_index" %>
</div>

app/views/estudios/new.html.erb
<%- model_class = Estudio -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estudios/show.html.erb
<%- model_class = Estudio -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @estudio.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @estudio.endereco %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              estudios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estudio_path(@estudio), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              estudio_path(@estudio),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>