config/routes.rb
Rails.application.routes.draw do
  get 'gif/cool'

  get 'gif/free'

  root to: 'gif#cool'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'  
  get '/sweet' => 'gif#sweet'  
   

  
  
  resources :estudios
  resources :eventos
  resources :compromissos
  resources :disciplinas
  resources :professores
  resources :welcome#index

end

app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
  validates_presence_of :titulo, :message => " - deve ser preenchido"
  validates_presence_of :texto, :message => "deve ser preenchido"	
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  has_many :disciplinas_mestres
  has_many :mestres, :through => :disciplinas_mestres
  has_many :eventos
  validates_presence_of :nome, :message => "- deve ser informado"

  validates_uniqueness_of :nome, :message => "Nome já informado"
	
end

app/models/disciplina_mestre.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/disciplina_professor.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  belongs_to :estudio
  validates_presence_of :data, :message => "Data deve ser preenchdida"
  validates_presence_of :hora_inicial, :message => "hora inicial deve ser informada"
  validates_presence_of :hora_final, :message => "hora final deve ser informada"  	
end

app/models/mestre.rb
class Mestre < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/compromissos_controller.rb
class CompromissosController < ApplicationController
  before_filter :authorize
  before_action :set_compromisso, only: [:show, :edit, :update, :destroy]
  
  # GET /compromissos
  # GET /compromissos.json
  def index
    if params[:search]                        
      @compromissos = Compromisso.where("titulo like ?", "%#{params[:search]}%")
      
    else 
      @compromissos = Compromisso.all.page(params['page']).per(5)
      @date = params[:month] ? Date.parse(params[:month]) : Date.today
    end
  end

  # GET /compromissos/1
  # GET /compromissos/1.json
  def show
  end

  # GET /compromissos/new
  def new
    @compromisso = Compromisso.new
  end

  # GET /compromissos/1/edit
  def edit
  end

  # POST /compromissos
  # POST /compromissos.json
  def create
    @compromisso = Compromisso.new(compromisso_params)

    respond_to do |format|
      if @compromisso.save
        format.html { redirect_to @compromisso, notice: 'Compromisso was successfully created.' }
        format.json { render :show, status: :created, location: @compromisso }
      else
        format.html { render :new }
        format.json { render json: @compromisso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compromissos/1
  # PATCH/PUT /compromissos/1.json
  def update
    respond_to do |format|
      if @compromisso.update(compromisso_params)
        format.html { redirect_to @compromisso, notice: 'Compromisso was successfully updated.' }
        format.json { render :show, status: :ok, location: @compromisso }
      else
        format.html { render :edit }
        format.json { render json: @compromisso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compromissos/1
  # DELETE /compromissos/1.json
  def destroy
    @compromisso.destroy
    respond_to do |format|
      format.html { redirect_to compromissos_url, notice: 'Compromisso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compromisso
      @compromisso = Compromisso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compromisso_params
      params.require(:compromisso).permit(:titulo, :texto, :date)
    end
end

app/controllers/gif_controller.rb
class GifController < ApplicationController
  before_filter :authorize
  def cool
    redirect_to '/welcome#index'
  end

  def free
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compromissos_helper.rb
module CompromissosHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/mestres_helper.rb
module MestresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/compromissos/_form.html.erb
<%= form_for @compromisso, :html => { :class => "form-horizontal compromisso" } do |f| %>

  <% if @compromisso.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@compromisso.errors.count, "error") %> prohibited this compromisso from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @compromisso.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:titulo) %>
  </div>
  <div class="form-group">
    <%= f.label :texto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :texto, :class => 'form-control' %>
    </div>
    <%=f.error_span(:texto) %>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.date_field :date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                compromissos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/compromissos/edit.html.erb
<%- model_class = Compromisso -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/compromissos/index.html.erb
<%- model_class = Compromisso -%>
<%= form_tag(compromissos_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Entre com sua busca' %>
  <%= submit_tag "Search" %>
<% end %>

<div id="calendar">
	<h2 id="month">
		<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
		<%=h @date.strftime("%B %Y") %>
		<%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
	</h2>
	<%= calendar_for @compromissos, :year => @date.year, :month => @date.month do |t| %>
	<%= t.head('DOM','SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB') %>
	<%= t.day do |day, compromissos| %>
	<%= day.day %>
	<% compromissos.each do |compromisso| %><br>
	<%= link_to h(compromisso.titulo), compromisso %><br>
	<%= link_to 'Editar', edit_compromisso_path(compromisso) %> | <%= link_to 'Deletar', compromisso, method: :delete, data: { confirm: 'Tem certeza?' } %>
	<% end %>
	<% end %>
	<% end %>
</div>
<%= link_to 'Novo Compromisso', new_compromisso_path %>

app/views/compromissos/new.html.erb
<%- model_class = Compromisso -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/compromissos/show.html.erb
<%- model_class = Compromisso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @compromisso.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:texto) %>:</strong></dt>
  <dd><%= @compromisso.texto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @compromisso.date %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              compromissos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_compromisso_path(@compromisso), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              compromisso_path(@compromisso),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>