config/routes.rb
Rails.application.routes.draw do
  get 'gif/cool'

  get 'gif/free'

  root to: 'gif#cool'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'  
  get '/sweet' => 'gif#sweet'  
   

  
  
  resources :estudios
  resources :eventos
  resources :compromissos
  resources :disciplinas
  resources :professores
  resources :welcome#index

end

app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
  validates_presence_of :titulo, :message => " - deve ser preenchido"
  validates_presence_of :texto, :message => "deve ser preenchido"	
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  has_many :disciplinas_mestres
  has_many :mestres, :through => :disciplinas_mestres
  has_many :eventos
  validates_presence_of :nome, :message => "- deve ser informado"

  validates_uniqueness_of :nome, :message => "Nome já informado"
	
end

app/models/disciplina_mestre.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/disciplina_professor.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  belongs_to :estudio
  validates_presence_of :data, :message => "Data deve ser preenchdida"
  validates_presence_of :hora_inicial, :message => "hora inicial deve ser informada"
  validates_presence_of :hora_final, :message => "hora final deve ser informada"  	
end

app/models/mestre.rb
class Mestre < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_filter :authorize
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  
  # GET /eventos
  # GET /eventos.json
  def index
     if params[:search]                                         
      @eventos = Evento.where("studio_id = ?", "%={params[:search]}%")
      
    else 
     # @disciplinas = Disciplina.all
     @eventos = Evento.all.page(params['page']).per(5)
    
    end  
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
    preparar_form
  end

  # GET /eventos/1/edit
  def edit
    preparar_form
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        preparar_form
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        preparar_form
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:disciplina_id, :professor_id, :estudio_id, :data, :hora_inicial, :hora_final)
    end
    def preparar_form
      @professores = Professor.order :nome
      @disciplinas = Disciplina.order :nome
      @estudios = Estudio.order :nome
    end

end

app/controllers/gif_controller.rb
class GifController < ApplicationController
  before_filter :authorize
  def cool
    redirect_to '/welcome#index'
  end

  def free
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compromissos_helper.rb
module CompromissosHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/mestres_helper.rb
module MestresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/eventos/_admin_index.html.erb
<%- model_class = Evento -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:disciplina_id) %></th>
      <th><%= model_class.human_attribute_name(:mestre_id) %></th>
      <th><%= model_class.human_attribute_name(:studio_id) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:hora_inicial) %></th>
      <th><%= model_class.human_attribute_name(:hora_final) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= link_to evento.id, evento_path(evento) %></td>
        <td><%= evento.disciplina_id %></td>
        <td><%= evento.mestre_id %></td>
        <td><%= evento.studio_id %></td>
        <td><%= evento.data %></td>
        <td><%= evento.hora_inicial %></td>
        <td><%= evento.hora_final %></td>
S
        <td>
          <%= link_to t('.show', :default => t("herpers.links.show")), evento_path(evento), :class => 'btn btn-success btn-xs'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_evento_path(evento), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      evento_path(evento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @eventos %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_evento_path,
            :class => 'btn btn-primary' %>

app/views/eventos/_form.html.erb
<%= form_for @evento, :html => { :class => "form-horizontal evento" } do |f| %>

  <% if @evento.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @evento.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :disciplina_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= collection_select(:evento, :disciplina_id, @disciplinas.all, :id, :nome, prompt: true)%>
    </div>
    <%=f.error_span(:disciplina_id) %>
    <%= f.label :professor_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= collection_select(:evento, :professor_id, @professores.all, :id, :nome, prompt: true)%>
    </div>
    <%=f.error_span(:professor_id) %>
  </div><br>
  <div class="form-group">
    <%= f.label :estudio_id, :class => 'control-label col-lg-2' %>
      <div class="col-lg-4">
      <%= collection_select(:evento, :estudio_id, @estudios.all, :id, :nome, prompt: true)%>
    </div>
     <%=f.error_span(:estudio_id) %>
     <%= f.label :data, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.date_field :data, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data) %>
  </div><br>
  <div class="form-group">
    <%= f.label :hora_inicial, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.time_field :hora_inicial, :class => 'form-control' %>
    </div>
    <%=f.error_span(:hora_inicial) %>
    <%= f.label :hora_final, :class => 'control-label col-lg-3' %>
    <div class="col-lg-3">
      <%= f.time_field :hora_final, :class => 'form-control' %>
    </div>
    <%=f.error_span(:hora_final) %>
  </div><br>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                eventos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/eventos/_normal_user_index.html.erb
<%- model_class = Evento -%>
<%= form_tag(eventos_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Entre com sua busca' %>
  <%= submit_tag "Search" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:disciplina_id) %></th>
      <th><%= model_class.human_attribute_name(:mestre_id) %></th>
      <th><%= model_class.human_attribute_name(:studio_id) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:hora_inicial) %></th>
      <th><%= model_class.human_attribute_name(:hora_final) %></th>
    </tr>
  </thead>
  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= link_to evento.id, evento_path(evento) %></td>
        <td><%= evento.disciplina_id %></td>
        <td><%= evento.mestre_id %></td>
        <td><%= evento.studio_id %></td>
        <td><%= evento.data %></td>
        <td><%= evento.hora_inicial %></td>
        <td><%= evento.hora_final %></td>
        <td>
          <%= link_to t('.show', :default => t("herpers.links.show")), evento_path(evento), :class => 'btn btn-success btn-xs'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_evento_path(evento), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      evento_path(evento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @eventos %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_evento_path,
            :class => 'btn btn-primary' %>

app/views/eventos/edit.html.erb
<%- model_class = Evento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/eventos/index.html.erb
<%- model_class = Evento -%>
<p id="notice" <%= notice %></p>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= render partial: "normal_user_index" %>
  
</div>

app/views/eventos/new.html.erb
<%- model_class = Evento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/eventos/show.html.erb
<%- model_class = Evento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:disciplina_id) %>:</strong></dt>
  <dd><%= @evento.disciplina_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mestre_id) %>:</strong></dt>
  <dd><%= @evento.mestre_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:studio_id) %>:</strong></dt>
  <dd><%= @evento.studio_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @evento.data %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_inicial) %>:</strong></dt>
  <dd><%= @evento.hora_inicial %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_final) %>:</strong></dt>
  <dd><%= @evento.hora_final %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              eventos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_evento_path(@evento), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              evento_path(@evento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>