config/routes.rb
Rails.application.routes.draw do
  get 'gif/cool'

  get 'gif/free'

  root to: 'gif#cool'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/cool' => 'gif#cool'  
  get '/sweet' => 'gif#sweet'  
   

  
  
  resources :estudios
  resources :eventos
  resources :compromissos
  resources :disciplinas
  resources :professores
  resources :welcome#index

end

app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
  validates_presence_of :titulo, :message => " - deve ser preenchido"
  validates_presence_of :texto, :message => "deve ser preenchido"	
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  has_many :disciplinas_mestres
  has_many :mestres, :through => :disciplinas_mestres
  has_many :eventos
  validates_presence_of :nome, :message => "- deve ser informado"

  validates_uniqueness_of :nome, :message => "Nome já informado"
	
end

app/models/disciplina_mestre.rb
class DisciplinaMestre < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :mestre	
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :professor
  belongs_to :estudio
  validates_presence_of :data, :message => "Data deve ser preenchdida"
  validates_presence_of :hora_inicial, :message => "hora inicial deve ser informada"
  validates_presence_of :hora_final, :message => "hora final deve ser informada"  	
end

app/models/mestre.rb
class Mestre < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/professor.rb
class Professor < ActiveRecord::Base
  mount_uploader :foto, PictureUploader
  has_many :disciplinas_mestres
  has_many :disciplinas, :through => :disciplinas_mestres

  has_many :eventos

  validates_presence_of :nome, :message => "deve ser preenchido"
  validates_presence_of :matricula, :message => "deve ser preenchida"
  validates_presence_of :email, :message => "deve ser informado"
  validates_presence_of :foto, :message => "A foto é necessário"

  validates_uniqueness_of :nome, :message => "- nome já cadastrado"
  validates_uniqueness_of :matricula, :message => "-matrícula já informada"
  validates_uniqueness_of :celular, :message => "celular já informado"
  validates_uniqueness_of :email, :message => "e-mail já informadop"	
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  validates_presence_of :nome, :message => "- deve ser informado"
  validates_presence_of :endereco, :message => "- deve ser informado"

  has_many :eventos

  validates_uniqueness_of :endereco, :message => "Endereço já informado"	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/gif_controller.rb
class GifController < ApplicationController
  before_filter :authorize
  def cool
    redirect_to '/welcome#index'
  end

  def free
  end
end

app/controllers/professores_controller.rb
class ProfessoresController < ApplicationController
  before_filter :authorize
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  
  # GET /professors
  # GET /professors.json
  def index    
    if params[:search]                        
      @professors = Professor.where("nome like ?", "%#{params[:search]}%")
      @professors = @professors.page(params['page']).per(5)
    else 
      # @professors = professor.all
      @professors = Professor.all.page(params['page']).per(5)
    end  
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professore = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :matricula, :celular, :email, :foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/estudios_helper.rb
module EstudiosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/gif_helper.rb
module GifHelper
end

app/helpers/mestres_helper.rb
module MestresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/professores/_admin_index.html.erb
<%- model_class = Professor -%>
<%= form_tag(professores_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Entre com sua busca' %>
  <%= submit_tag "Search" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:matricula) %></th>
      <th><%= model_class.human_attribute_name(:celular) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:foto) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= link_to professor.id, professore_path(professor) %></td>
        <td><%= professor.nome %></td>
        <td><%= professor.matricula %></td>
        <td><%= professor.celular %></td>
        <td><%= professor.email %></td>
        <td><%= professor.foto %></td>
        <td>
          <%= link_to t('.show', :default => t("herpers.links.show")), professore_path(professor), :class => 'btn btn-success btn-xs'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_professore_path(professor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      professore_path(professor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @professors %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_professore_path,
            :class => 'btn btn-primary' %>

app/views/professores/_form.html.erb
<%= form_for @professor, :html => { :class => "form-horizontal professor" } do |f| %>

  <% if @professor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @professor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :matricula, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :matricula, :class => 'form-control' %>
    </div>
    <%=f.error_span(:matricula) %>
  </div>
  <div class="form-group">
    <%= f.label :celular, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :celular, :class => 'form-control' %>
    </div>
    <%=f.error_span(:celular) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :foto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.file_field :foto, :class => 'form-control' %>
    </div>
    <%=f.error_span(:foto) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                professores_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/professores/_normal_user_index.html.erb
<%- model_class = Professor -%>
<%= form_tag(professores_path, :method => :get) do %>
  <%= text_field_tag 'search', nil, placeholder: 'Entre com sua busca' %>
  <%= submit_tag "Search" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:matricula) %></th>
      <th><%= model_class.human_attribute_name(:celular) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:foto) %></th>
    </tr>
  </thead>
  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= link_to professor.id, professore_path(professor) %></td>
        <td><%= professor.nome %></td>
        <td><%= professor.matricula %></td>
        <td><%= professor.celular %></td>
        <td><%= professor.email %></td>
        <td><%= professor.foto %></td>
        <td>
          <%= link_to t('.show', :default => t("herpers.links.show")), professore_path(professor), :class => 'btn btn-success btn-xs'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_professore_path(professor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      professore_path(professor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @professors %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_professore_path,
            :class => 'btn btn-primary' %>

app/views/professores/edit.html.erb
<%- model_class = Professor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/professores/index.html.erb
<%- model_class = Professor -%>
<p id="notice" <%= notice %></p>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= render partial: "normal_user_index" %>
</div>

app/views/professores/new.html.erb
<%- model_class = Professor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/professores/show.html.erb
<%- model_class = Professor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @professor.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:matricula) %>:</strong></dt>
  <dd><%= @professor.matricula %></dd>
  <dt><strong><%= model_class.human_attribute_name(:celular) %>:</strong></dt>
  <dd><%= @professor.celular %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @professor.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:foto) %>:</strong></dt>
  <dd>  <%=image_tag(@professor.foto_url, :width => 200) if @professor.foto.present? %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              professores_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_professore_path(@professor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              professore_path(@professor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>